- platform: bom
  station: IDW60901.94608
  name: "Perth"
  monitored_conditions:
    - air_temp
    - apparent_t
    - rel_hum
    - rain_trace

- platform: transmission
  host: 10.0.1.21
  port: 9091
  name: "dorado tx"
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'