- platform: broadlink
  host: rmliving.mcfly.net
  mac: '78:0F:77:00:24:B1'
  type: rm_mini
  switches:
    living_tv_power:
      friendly_name: "TV Power"
      command_on: 'JgBGAJWSFTYUNhM3FBEUERQSExITEhM3EzcTNxQSExITEhMSEhMSExI4EjgTExITEjgSOBI4EzgSExITEjgSOBITExITExIADQUAAA=='
      command_off: 'JgBGAJWSFTYUNhM3FBEUERQSExITEhM3EzcTNxQSExITEhMSEhMSExI4EjgTExITEjgSOBI4EzgSExITEjgSOBITExITExIADQUAAA=='
    living_amp_power:
      friendly_name: "Amp Power"
      command_on: 'JgBQAAABKpIUERQ2FBEUERQ2FBEUERQRFBEUERQ2FBEUNRU1FRAVEBU1FRAVEBUQFRAVEBURFBEUERQ1FTUVNRQ2FDYUNRU1FQAFjwABKUgVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpIUERQ2FBEUERQ2FBEUERQRFBEUERQ2FBEUNRU1FRAVEBU1FRAVEBUQFRAVEBURFBEUERQ1FTUVNRQ2FDYUNRU1FQAFjwABKUgVAA0FAAAAAAAAAAA='
    living_amp_menu:
      friendly_name: "Amp Menu"
      command_on: 'JgBQAAABKJQSExI3ExMSExI3ExITEhMTEhMSExI3ExITNxM3EhMSExMSExITNxITEhMTEhMSExITNxI4EhMSOBI4EjcTNxM3EgAFkgABJ0oSAA0FAAAAAAAAAAA='
    living_amp_vol_up:
      friendly_name: "Amp Volume Up"
      command_on: 'JgBQAAABJ5QTEhM3EhMSExI4EhMSExITEhMSExI4EhMSOBI3ExMSExITEjcTEhMSExITEhMTEhMSNxMSEzcSOBI4EjcTNxM3EgAFkQABJ0oTAA0FAAAAAAAAAAA='
    living_amp_vol_down:
      friendly_name: "Amp Volume Down"
      command_on: 'JgBQAAABJ5USExI4EhMSExI3ExMSExITEhMSExI4EhMSOBI3ExITExITEjcTNxMSExITEhMTEhMSNxMSExMSNxM3EzcSOBQ2EgAFkQABKkgVAA0FAAAAAAAAAAA='
    living_amp_cursor_left:
      friendly_name: "Amp Cursor Left"
      command_on: 'JgBQAAABKJQSExI4EhMSExI4EhMSExITEhMSExI4EhMSOBI3ExITEhM3EzcSExMSExITEhMSExITEhMTEjcTNxM3EjgSOBI3EwAFkQABJ0sSAA0FAAAAAAAAAAA='
    living_amp_cursor_right:
      friendly_name: "Amp Cursor Right"
      command_on: 'JgBQAAABKJQSExI3ExMSExI3ExITExITEhMSExI4EhMSNxM3ExITEhM3ExITNxITEhMTEhMSExITEhM3ExITNxM3EjgSOBI3EwAFkgABKUgVAA0FAAAAAAAAAAA='
    living_amp_mute:
      friendly_name: "Amp Mute"
      command_on: 'JgBQAAABKJMUERQ2FBEUERQ2ExITEhMSFBEUERQ2ExIUNhQ2FBEUERM3FBEUERQ2FBETEhQRExITEhM3FDYUERM2FTUVNRU1FAAFkAABKUgVAA0FAAAAAAAAAAA='
    living_amp_input:
      friendly_name: "Amp Input"
      command_on: 'JgBQAAABJ5QTEhM3ExITEhM3ExITEhMSExITEhM3ExITNxM3EhMSExM3EjgSOBITEhMSExITEhMSExITEhMSOBI4EjgSNxM3EwAFkQABKEoSAA0FAAAAAAAAAAA='
    living_amp_eq:
      friendly_name: "Amp EQ"
      command_on: 'JgBQAAABKpIUERQ2FBEUERQ1FREUERQRFBEUERQ2FBEUNhQ1FRAVERQRFBEUERQ2FBEUERQRFBEUNhQ1FTUVEBU1FTUVNRU1FAAFkAABKkcVAA0FAAAAAAAAAAA='
    living_ac_power:
      friendly_name: "AC Power"
      command_on: 'JgAGAW00EAwPDQ8nDw0PJw8NDw0PDA8oDycPDQ8MEAwPKA8nDw0PDA8NDw0PDA8NDw0PDA8NDw0PDA8NDw0PJw8NDwwQDA8NDwwQDA8NDycPDQ8NDwwPDQ8nDygPJw8oDycPKA8nDygPDA8NDycPDQ8NDwwPDQ8NDwwPDQ8NDycPKA8MDw0PJw8NDw0PDA8NDycQJw8NDycPDQ8MDw0PDQ8MDw0PDQ8MDw0PDQ8MDw0PDQ8MDw0PDQ8MDw0PJw8NDw0PDA8NDycQJw8MEAwPDQ8MEAwPDQ8MECcPJxAMDygPDA8oDwwPKA8MEAwPDQ8MECcPDBAMDw0PDBAnDycQDA8nECcPJxAADQUAAA=='
      command_off: 'JgB2AG40Dw0PDQ4oDw0OKA8NDg4ODg4nDygPDQ4ODg0PJw8nEA0ODg4NDwwPDg4NDw0ODg4NDw0ODg4MEA0OJxANDg4ODQ8NDg4ODQ8NDigPDQ4ODg0PDQ4oDw0ODQ8ODg0ODg4ODicPDg4nDygPJw8oDycPKA8ADQUAAA=='
    living_ac_temp_up:
      friendly_name: "AC Temp Up"
      command_on: 'JgAGAW00EAwPDQ8nEAwPJxAMDw0PDBAnDycQDA8NDwwQJw8nDw0PDQ8MDw0PDQ8MDw0PDBAMDw0PDBAMDw0PJxAMDw0PDBAMDw0PDBAMDycQDA8NDwwQDA8nECcPJxAnDycQJw8nECcPDBAMDygPDA8NDw0PDA8NDw0PDA8NDycQJw8MEAwPDQ8MEAwPDQ8nECcPJw8NDwwQDA8NDwwQDA8NDwwQDA8NDwwQDA8NDwwQDA8NDwwQDA8NDwwQDA8oDwwPDQ8NDycPJxAMDw0PDBAMDw0PDBAMDw0PDBAMDw0PDBAnDw0PJw8NDwwQDA8NDycPDQ8MEAwPDQ8nECcPDBAnDycQJw8ADQUAAA=='
    living_ac_temp_down:
      friendly_name: "AC Temp Down"
      command_on: 'JgAGAW40Dw0PDQ4oDw0OKA8NDw0ODg4nDygPDQ4NDw0PJw8oDw0ODg4ODg0ODg4NDw0ODQ8NDw0ODg4NDw0OKA8NDw0ODg4NDg4ODg4NDycPDQ8NDg4ODQ8nDycQJw8nECcPJw8oDycPDg4NDycPDg4NDg4ODg4NDg4ODg4NDigPJw8ODg0PDQ4ODg0PDQ4oDycPKA8NDg4ODQ8NDg4ODg4NDg4ODQ8NDg4ODQ8NDg4ODQ8NDg4ODQ8NDg4ODQ8nDw0PDQ8NDigPJw8ODg0ODg4ODg0ODQ8nECcPDQ8MDw4ODQ8nDw4OJw8ODg0PDQ4ODicPDg4ODicPDg4NDycPDQ8nDycQJw8ADQUAAA=='
    living_ac_mode:
      friendly_name: "AC Mode"
      command_on: 'JgAGAW00Dw0PDQ8nDw0PJw8NDw0PDQ4oDycPDQ8MEAwPKA8nDw0PDBAMDw0PDBAMDw0PDBAMDw0PDBAMDw0PJw8NDw0PDA8NDw0PDA8NDycPDQ8NDwwPDQ8nECcPJxAnDycPKA8nDygPDBAMDycQDA8NDwwQDA8NDwwQDA8NDycPKA8MEAwPDQ8MEAwPDQ8nDygPJw8NDycPDQ8NDwwPDQ8NDwwPDQ8NDwwPDQ8NDwwPDQ8NDwwPDQ8NDwwPDQ8nEAwPDQ8MECcPJw8NDw0PDA8NDw0PDA8oDwwQJw8MEAwPDQ8nDw0PJxAMDw0PDBAMDygPDA8NDw0PJw8nEAwPDQ8nDygPJw8ADQUAAA=='
    living_ac_fan:
      friendly_name: "AC Fan"
      command_on: 'JgAGAW01Dw0ODg4nDw4OJxANDg0PDQ8nDycQDQ4ODg0PJw8nDw4ODg4NDg4ODg4NDg4ODg4NDg4ODg4NDg4OJxAMDw4ODQ8NDg4ODQ8NDigPDA8ODg0PDQ4oDycPKA8nDygPJw8nECcPDQ8MDygPDBANDg4ODQ4ODg4ODQ4ODigPJw8NDw0ODg4ODg0ODg4nECcPJw8ODg4ODQ4ODg4ODQ4ODg4ODQ4oDw0PDQ4ODg0PDQ4ODg0PDQ4ODg0PDQ4oDw0ODg4NDycPJxAMDw4ODQ8NDg0PDQ8NDigPJw8ODg0PDQ4nEA0OKA8NDg4ODg4NDigPDQ8NDigPDQ4oDw0ODg4nECcPJxAADQUAAA=='
    living_ac_economy:
      friendly_name: "AC Economy"
      command_on: 'JgB2AG40DwwQDA8oDwwPKA8MEAwPDQ8nDygPDA8NDw0PJw8oDwwPDQ8NDwwPDQ8NDwwPDQ8NDwwPDQ8NDwwPKA8MEAwPDQ8MEAwPDQ8MECcPDBAMDw0PJw8NDw0PJw8NDwwQDA8NDwwQJw8nDw0PJxAnDycQJw8ADQUAAA=='
    living_ac_energysaver:
      friendly_name: "AC Energy Saver"
      command_on: 'JgAGAW40Dw0PDBAnDwwQJw8NDwwPDQ8nECcPDBAMDw0PJw8oDwwQDA8NDwwQDA8NDwwQDA8NDwwQDA8NDwwQJw8NDwwPDQ8NDwwPDQ8NDycPDQ8MDw0PDQ8nDygPJw8oDycPJxAnDycPDQ8NDycPDQ8NDwwPDQ8NDwwPDQ8NDycPJxAMDw0PDBAMDw0PDBAnDycPKA8MEAwPDQ8MEAwPDQ8MEAwPDQ8nDw0PDQ8MDw0PDQ8MDw0PDQ8MDw0PDQ8nDw0PDA8NDygPJw8NDwwPDQ8NDwwPDQ8nEAwPDQ8nDw0PDQ8nDw0PDA8NDw0PDA8NDycQDA8NDycPKA8MEAwPDQ8nDygPJw8ADQUAAA=='
    living_ac_swing:
      friendly_name: "AC Swing"
      command_on: 'JgAGAW00Dw0PDQ8nDw0PJw8NDwwQDA8oDycPDQ8MEAwPKA8nDw0PDA8NDw0PDA8NDw0PDA8NDw0PDA8NDw0PJw8NDwwQDA8NDwwQDA8NDycPDQ8NDwwPDQ8nECcPJw8oDycPKA8nDygPDA8NDycQDA8NDwwQDA8NDwwQDA8NDycPKA8MDw0PDQ8MDw0PDQ8nDygPJw8NDwwPDQ8NDwwPDQ8NDwwPDQ8oDwwPDQ8MECcPDQ8MDw0PDQ8MDw0PDQ8nDw0PDBAMDygPJw8NDwwPDQ8NDwwPDQ8nEAwPDQ8nDw0PDQ8nDw0PDA8NDw0PDA8NDycQDA8NDycPKA8MEAwPKA8MDygPJw8ADQUAAA=='
    living_ac_set_horizontal:
      friendly_name: "AC Set Horizontal"
      command_on: 'JgB2AG40EAwPDBAnDw0PJw8NDwwQDA8oDycPDQ8MEAwPJxAnDw0PDBAMDw0PDBAMDw0PDBAMDw0PDBAMDw0PJw8NDwwQDA8NDwwQDA8NDycPDQ8MEAwPKA8MEAwPJxAnDycQJw8MEAwPKA8nDw0PDBAMDw0PJxAADQUAAA=='
    living_ac_set_vertical:
      friendly_name: "AC Set Vertical"
      command_on: 'JgB2AG40DwwQDA8nEAwPKA8MEAwPDQ8nDycQDA8NDwwQJw8nEAwPDQ8MEAwPDQ8MEAwPDQ8MEAwPDQ8MEAwPJxAMDw0PDBAMDw0PDQ8MDygPDBAMDw0PDBAMDycQJw8NDycPJxAMDygPJw8NDwwQJw8NDwwQJw8ADQUAAA=='
    